#ifndef PROTOCOL_STATES_H
#define PROTOCOL_STATES_H

#define STATE_SHIELD_OPEN     250
#define STATE_SHIELD_CLOSE    200
#define STATE_PLATE_UP        350
#define STATE_PLATE_DOWN      300
#define STATE_SAMPLE_NEXT     100
#define STATE_SAMPLE_PREV     150
#define STATE_UNKNOWN           0
#define STATE_EMERGENCY_STOP 499


#endif
